#!/usr/bin/env bash

flakes=(hs-pcap/hs-pcap-client hs-pcap/hs-pcap-th hs-wlroots)

for flake in "${flakes[@]}"; do
    (
        cd "$flake" || exit 1
        nix flake update
    )
done

nix flake update
nix flake check
