#!/usr/bin/env bash

include_graph_flags=(
    --include "pcap"
)

module_flags=(
    --overwrite-files
)

hs-bindgen-cli info include-graph \
    "${module_flags[@]}" \
    "${include_graph_flags[@]}" \
    pcap.h -o pcap.mmd
