#!/usr/bin/env bash

module_flags=(
    --hs-output-dir src
    --module Generated.Pcap
)

c_flags=(
    # Enable GNU extensions. GNU extensions define types, such as `u_int`, which
    # `libpcap` requires.
    --gnu
)

parse_flags=(
    # TODO https://github.com/well-typed/hs-bindgen/issues/1178: Why do we need
    # `--parse-all`? We get "unavailable transitive dependencies" if we do not
    # use `--parse-all`.
    --parse-all
)

select_flags=(
    # `pcap.h` itself does not define any declarations, but only includes
    # `pcap/pcap.h`. Tell `hs-bindgen` to also select bindings from other
    # headers matching Pearl-compatible regular expression ".*pcap\.h.*".
    --select-by-header-path pcap.h
    # Select transitive dependencies.
    --enable-program-slicing
    --select-except-deprecated
)

debug_flags=(
    # Run `hs-bindgen` with log level "Info".
    -v3
    # # Run `hs-bindgen` with log level "Debug".
    # -v4
)

hs-bindgen-cli preprocess \
    "${module_flags[@]}" \
    "${c_flags[@]}" \
    "${parse_flags[@]}" \
    "${select_flags[@]}" \
    "${debug_flags[@]}" \
    pcap.h
