#!/usr/bin/env bash

module_flags=(
    --hs-output-dir src
    --module Generated.Pcap
)

c_flags=(
    # Enable GNU extensions. GNU extensions define types, such as `u_int`, which
    # `libpcap` requires.
    --gnu
)

parse_flags=(
    # TODO https://github.com/well-typed/hs-bindgen/issues/1178: Why do we need
    # `--parse-all`? We get "unavailable transitive dependencies" if we do not
    # use `--parse-all`.
    --parse-all
)

select_flags=(
    # `pcap.h` itself does not define any declarations, but only includes
    # `pcap/pcap.h`. Tell `hs-bindgen` to also select bindings from other
    # headers matching Pearl-compatible regular expression ".*pcap\.h.*".
    --select-by-header-path pcap.h
    # Select transitive dependencies.
    --enable-program-slicing
    --select-except-deprecated
    # We manually de-select some declarations. These declarations are only
    # available when `libpcap` is built with "remote capture" enabled, which is
    # not the case by default in Nixpkgs.
    --select-except-by-decl-name 'pcap_open'
    --select-except-by-decl-name 'pcap_createsrcstr'
    --select-except-by-decl-name 'pcap_parsesrcstr'
    --select-except-by-decl-name 'pcap_findalldevs_ex'
    --select-except-by-decl-name 'pcap_setsampling'
    --select-except-by-decl-name 'pcap_remoteact_accept'
    --select-except-by-decl-name 'pcap_remoteact_accept_ex'
    --select-except-by-decl-name 'pcap_remoteact_list'
    --select-except-by-decl-name 'pcap_remoteact_close'
    --select-except-by-decl-name 'pcap_remoteact_cleanup'
)

debug_flags=(
    # Run `hs-bindgen` with log level "Info".
    -v3
    # # Run `hs-bindgen` with log level "Debug".
    # -v4
)

hs-bindgen-cli preprocess \
    "${module_flags[@]}" \
    "${c_flags[@]}" \
    "${parse_flags[@]}" \
    "${select_flags[@]}" \
    "${debug_flags[@]}" \
    pcap.h
