#!/usr/bin/env bash

debug=(-v 2)

wayland-util() {
    local header="wayland-util.h"

    local c_flags=(
    )

    local parse_flags=(
        --parse-all
    )

    local select_flags=(
        --select-except-deprecated
        --enable-program-slicing
    )

    local module_flags=(
        --unique-id com.hs-bindgen.wayland-util
        --module Generated.Wayland.Util
        --hs-output-dir src
        --create-output-dirs
        --overwrite-files
    )

    local binding_specs_flags=(
        --gen-binding-spec WaylandUtil.yaml
    )

    hs-bindgen-cli preprocess "${header}" \
        "${debug[@]}" \
        "${c_flags[@]}" \
        "${parse_flags[@]}" \
        "${select_flags[@]}" \
        "${module_flags[@]}" \
        "${binding_specs_flags[@]}"
}

wayland-core() {
    local header="wayland-server-core.h"

    local c_flags=(
    )

    local parse_flags=(
        --parse-all
    )

    local select_flags=(
        --select-except-deprecated
        --enable-program-slicing
    )

    local module_flags=(
        --unique-id com.hs-bindgen.wayland-server-core
        --module Generated.Wayland.Server.Core
        --hs-output-dir src
        --create-output-dirs
        --overwrite-files
    )

    local binding_specs_flags=(
        --external-binding-spec WaylandUtil.yaml
        --gen-binding-spec WaylandServerCore.yaml
    )

    hs-bindgen-cli preprocess "${header}" \
        "${debug[@]}" \
        "${c_flags[@]}" \
        "${parse_flags[@]}" \
        "${select_flags[@]}" \
        "${module_flags[@]}" \
        "${binding_specs_flags[@]}"
}

pixman() {
    local header="pixman.h"

    local c_flags=(
    )

    local parse_flags=(
        --parse-all
    )

    local select_flags=(
        --select-by-header-path "${header}"
        --select-except-deprecated
        --enable-program-slicing
    )

    local module_flags=(
        --unique-id com.hs-bindgen.pixman
        --module Generated.Pixman
        --hs-output-dir src
        --create-output-dirs
        --overwrite-files
    )

    local binding_specs_flags=(
        --external-binding-spec WaylandUtil.yaml
        --external-binding-spec WaylandServerCore.yaml
        --gen-binding-spec Pixman.yaml
    )

    hs-bindgen-cli preprocess "${header}" \
        "${debug[@]}" \
        "${c_flags[@]}" \
        "${parse_flags[@]}" \
        "${select_flags[@]}" \
        "${module_flags[@]}" \
        "${binding_specs_flags[@]}"
}

wlr-types-output() {
    local header="wlr/types/wlr_output.h"

    local c_flags=(
        # Enable unstable features of Wlroots.
        --clang-option -DWLR_USE_UNSTABLE
    )

    local parse_flags=(
        --parse-all
    )

    local select_flags=(
        --select-by-header-path "${header}"
        --select-except-deprecated
        --enable-program-slicing
    )

    local module_flags=(
        --unique-id com.hs-bindgen.wlr.output
        --module Generated.Wlr.Types.Output
        --hs-output-dir src
        --create-output-dirs
        --overwrite-files
    )

    local binding_specs_flags=(
        --external-binding-spec WaylandUtil.yaml
        --external-binding-spec WaylandServerCore.yaml
        --external-binding-spec Pixman.yaml
        --gen-binding-spec WlrTypesOutput.yaml
    )

    hs-bindgen-cli preprocess "${header}" \
        "${debug[@]}" \
        "${c_flags[@]}" \
        "${parse_flags[@]}" \
        "${select_flags[@]}" \
        "${module_flags[@]}" \
        "${binding_specs_flags[@]}"
}

wlr-backend() {
    local header="wlr/backend.h"

    local c_flags=(
        # Enable unstable features of Wlroots.
        --clang-option -DWLR_USE_UNSTABLE
    )

    local parse_flags=(
        --parse-all
    )

    local select_flags=(
        --select-by-header-path "${header}"
        --select-except-deprecated
        --enable-program-slicing
    )

    local module_flags=(
        --unique-id com.hs-bindgen.wlr.backend
        --module Generated.Wlr.Backend
        --hs-output-dir src
        --create-output-dirs
        --overwrite-files
    )

    local binding_specs_flags=(
        --external-binding-spec WaylandUtil.yaml
        --external-binding-spec WaylandServerCore.yaml
        --external-binding-spec Pixman.yaml
        --external-binding-spec WlrTypesOutput.yaml
    )

    hs-bindgen-cli preprocess "${header}" \
        "${debug[@]}" \
        "${c_flags[@]}" \
        "${parse_flags[@]}" \
        "${select_flags[@]}" \
        "${module_flags[@]}" \
        "${binding_specs_flags[@]}"
}

wayland-util
wayland-core
pixman
wlr-types-output
wlr-backend
