#!/usr/bin/env bash

BINDGEN=hs-bindgen-cli

header="wlr/backend.h"

debug=(-v 2)

c_flags=(
    # Enable unstable features of Wlroots. A `--hash-define` applies to the
    # headers that follow it.
    --hash-define WLR_USE_UNSTABLE 1
)

module_flags=(
    --overwrite-files
)

generate_include_graph() {
    "${BINDGEN}" info include-graph "${c_flags[@]}" "${header}" \
        "${debug[@]}" \
        "${module_flags[@]}" \
        "$@"
}

generate_include_graph -o include-graph-all.mmd

generate_include_graph -o include-graph-backend.mmd \
    --include "wlroots"

generate_include_graph -o include-graph-no-stdlibs.mmd \
    --exclude "glibc" --exclude "lib/clang/"
