#!/usr/bin/env bash

BINDGEN=hs-bindgen-cli

header="wlr/backend.h"

debug=(-v 2)

c_flags=(
    # Enable unstable features of Wlroots.
    --clang-option -DWLR_USE_UNSTABLE
)

module_flags=(
    --overwrite-files
)

generate_include_graph() {
    "${BINDGEN}" info include-graph "${header}" \
        "${debug[@]}" \
        "${c_flags[@]}" \
        "${module_flags[@]}" \
        "$@"
}

generate_include_graph -o include-graph-all.mmd

generate_include_graph -o include-graph-backend.mmd \
    --include "wlroots"

generate_include_graph -o include-graph-backend-simple.mmd \
    --include "wlroots" --simple

generate_include_graph -o include-graph-no-stdlibs.mmd \
    --exclude "glibc" --exclude "clang-wrapper"

generate_include_graph -o include-graph-no-stdlibs-simple.mmd \
    --exclude "glibc" --exclude "clang-wrapper" --simple
