%% Manually simplified include graph when parsing all transitive dependencies.

graph TD;
  v58["/nix/store/1cnvyk57f3wqlmbpidz0x2824ip9f8ly-pixman-0.46.4/include/pixman-version.h"]
  v57["/nix/store/1cnvyk57f3wqlmbpidz0x2824ip9f8ly-pixman-0.46.4/include/pixman.h"]
  v2["/nix/store/c3q7cp0nbvndl38znhqw3daihnirqj3g-wayland-1.24.0-dev/include/wayland-server-core.h"]
  v66["/nix/store/c3q7cp0nbvndl38znhqw3daihnirqj3g-wayland-1.24.0-dev/include/wayland-server-protocol.h"]
  v67["/nix/store/c3q7cp0nbvndl38znhqw3daihnirqj3g-wayland-1.24.0-dev/include/wayland-server.h"]
  v29["/nix/store/c3q7cp0nbvndl38znhqw3daihnirqj3g-wayland-1.24.0-dev/include/wayland-util.h"]
  v55["/nix/store/c3q7cp0nbvndl38znhqw3daihnirqj3g-wayland-1.24.0-dev/include/wayland-version.h"]
  v0["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/backend.h"]
  v72["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/render/dmabuf.h"]
  v69["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/render/pass.h"]
  v68["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/render/wlr_renderer.h"]
  v71["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/render/wlr_texture.h"]
  v73["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/types/wlr_buffer.h"]
  v56["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/types/wlr_output.h"]
  v74["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/util/addon.h"]
  v70["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/util/box.h"]
  v0-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v67-->|"#include &quot;wayland-server-core.h&quot;"|v2
  v68-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v69-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v71-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v73-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v74-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v2-->|"#include &quot;wayland-util.h&quot;"|v29
  v56-->|"#include &lt;wayland-util.h&gt;"|v29
  v2-->|"#include &quot;wayland-version.h&quot;"|v55
  v0-->|"#include &lt;wlr/types/wlr_output.h&gt;"|v56
  v56-->|"#include &lt;pixman.h&gt;"|v57
  v69-->|"#include &lt;pixman.h&gt;"|v57
  v71-->|"#include &lt;pixman.h&gt;"|v57
  v73-->|"#include &lt;pixman.h&gt;"|v57
  v57-->|"#include &lt;pixman-version.h&gt;"|v58
  v56-->|"#include &lt;wayland-server-protocol.h&gt;"|v66
  v67-->|"#include &quot;wayland-server-protocol.h&quot;"|v66
  v70-->|"#include &lt;wayland-server-protocol.h&gt;"|v66
  v66-->|"#include &quot;wayland-server.h&quot;"|v67
  v56-->|"#include &lt;wlr/render/wlr_renderer.h&gt;"|v68
  v68-->|"#include &lt;wlr/render/pass.h&gt;"|v69
  v56-->|"#include &lt;wlr/util/box.h&gt;"|v70
  v68-->|"#include &lt;wlr/util/box.h&gt;"|v70
  v69-->|"#include &lt;wlr/util/box.h&gt;"|v70
  v71-->|"#include &lt;wlr/util/box.h&gt;"|v70
  v68-->|"#include &lt;wlr/render/wlr_texture.h&gt;"|v71
  v71-->|"#include &lt;wlr/render/dmabuf.h&gt;"|v72
  v73-->|"#include &lt;wlr/render/dmabuf.h&gt;"|v72
  v56-->|"#include &lt;wlr/types/wlr_buffer.h&gt;"|v73
  v56-->|"#include &lt;wlr/util/addon.h&gt;"|v74
  v73-->|"#include &lt;wlr/util/addon.h&gt;"|v74
