graph TD;
  v0["wlroots-0.19/wlr/backend.h"]
  v90["wlroots-0.19/wlr/render/dmabuf.h"]
  v87["wlroots-0.19/wlr/render/pass.h"]
  v86["wlroots-0.19/wlr/render/wlr_renderer.h"]
  v89["wlroots-0.19/wlr/render/wlr_texture.h"]
  v91["wlroots-0.19/wlr/types/wlr_buffer.h"]
  v75["wlroots-0.19/wlr/types/wlr_output.h"]
  v92["wlroots-0.19/wlr/util/addon.h"]
  v88["wlroots-0.19/wlr/util/box.h"]
  v0-->v75
  v75-->v86
  v86-->v87
  v75-->v88
  v86-->v88
  v87-->v88
  v89-->v88
  v86-->v89
  v89-->v90
  v91-->v90
  v75-->v91
  v75-->v92
  v91-->v92
