graph TD
  v0("wlr/backend.h")
  v2("wayland-server-core.h")
  v3("sys/types.h")
  v4("features.h")
  v5("features-time64.h")
  v6("bits/wordsize.h")
  v7("bits/timesize.h")
  v8("stdc-predef.h")
  v9("sys/cdefs.h")
  v10("bits/long-double.h")
  v11("gnu/stubs.h")
  v12("gnu/stubs-64.h")
  v13("bits/types.h")
  v14("bits/typesizes.h")
  v15("bits/time64.h")
  v16("bits/types/clock_t.h")
  v17("bits/types/clockid_t.h")
  v18("bits/types/time_t.h")
  v19("bits/types/timer_t.h")
  v20("stddef.h")
  v21("__stddef_size_t.h")
  v22("bits/stdint-intn.h")
  v23("endian.h")
  v24("bits/endian.h")
  v25("bits/endianness.h")
  v26("bits/byteswap.h")
  v27("bits/uintn-identity.h")
  v28("sys/select.h")
  v29("bits/select.h")
  v30("bits/types/sigset_t.h")
  v31("bits/types/__sigset_t.h")
  v32("bits/types/struct_timeval.h")
  v33("bits/types/struct_timespec.h")
  v34("bits/pthreadtypes.h")
  v35("bits/thread-shared-types.h")
  v36("bits/pthreadtypes-arch.h")
  v37("bits/atomic_wide_counter.h")
  v38("bits/struct_mutex.h")
  v39("bits/struct_rwlock.h")
  v40("stdint.h")
  v41("stdint.h")
  v42("bits/libc-header-start.h")
  v43("bits/wchar.h")
  v44("bits/stdint-uintn.h")
  v45("bits/stdint-least.h")
  v46("stdbool.h")
  v47("wayland-util.h")
  v48("math.h")
  v49("bits/math-vector.h")
  v50("bits/libm-simd-decl-stubs.h")
  v51("bits/floatn.h")
  v52("bits/floatn-common.h")
  v53("bits/flt-eval-method.h")
  v54("bits/fp-logb.h")
  v55("bits/fp-fast.h")
  v56("bits/mathcalls-macros.h")
  v57("bits/mathcalls-helper-functions.h")
  v58("bits/mathcalls.h")
  v59("__stddef_header_macro.h")
  v60("__stddef_ptrdiff_t.h")
  v61("__stddef_wchar_t.h")
  v62("__stddef_null.h")
  v63("__stddef_max_align_t.h")
  v64("__stddef_offsetof.h")
  v65("inttypes.h")
  v66("inttypes.h")
  v67("stdarg.h")
  v68("__stdarg_header_macro.h")
  v69("__stdarg___gnuc_va_list.h")
  v70("__stdarg_va_list.h")
  v71("__stdarg_va_arg.h")
  v72("__stdarg___va_copy.h")
  v73("__stdarg_va_copy.h")
  v74("wayland-version.h")
  v75("wlr/types/wlr_output.h")
  v76("pixman.h")
  v77("pixman-version.h")
  v78("time.h")
  v79("bits/time.h")
  v80("bits/types/struct_tm.h")
  v81("bits/types/struct_itimerspec.h")
  v82("bits/types/locale_t.h")
  v83("bits/types/__locale_t.h")
  v84("wayland-server-protocol.h")
  v85("wayland-server.h")
  v86("wlr/render/wlr_renderer.h")
  v87("wlr/render/pass.h")
  v88("wlr/util/box.h")
  v89("wlr/render/wlr_texture.h")
  v90("wlr/render/dmabuf.h")
  v91("wlr/types/wlr_buffer.h")
  v92("wlr/util/addon.h")
  v0-->v2
  v85-->v2
  v86-->v2
  v87-->v2
  v89-->v2
  v91-->v2
  v92-->v2
  v2-->v3
  v3-->v4
  v13-->v4
  v23-->v4
  v26-->v4
  v28-->v4
  v42-->v4
  v51-->v4
  v52-->v4
  v66-->v4
  v78-->v4
  v4-->v5
  v5-->v6
  v7-->v6
  v9-->v6
  v13-->v6
  v36-->v6
  v41-->v6
  v5-->v7
  v13-->v7
  v4-->v8
  v4-->v9
  v9-->v10
  v52-->v10
  v4-->v11
  v11-->v12
  v3-->v13
  v16-->v13
  v17-->v13
  v18-->v13
  v19-->v13
  v22-->v13
  v26-->v13
  v27-->v13
  v28-->v13
  v32-->v13
  v33-->v13
  v41-->v13
  v44-->v13
  v45-->v13
  v48-->v13
  v79-->v13
  v80-->v13
  v81-->v13
  v13-->v14
  v13-->v15
  v3-->v16
  v78-->v16
  v3-->v17
  v78-->v17
  v3-->v18
  v28-->v18
  v33-->v18
  v78-->v18
  v3-->v19
  v78-->v19
  v3-->v20
  v47-->v20
  v78-->v20
  v84-->v20
  v20-->v21
  v3-->v22
  v41-->v22
  v3-->v23
  v23-->v24
  v33-->v24
  v24-->v25
  v23-->v26
  v23-->v27
  v3-->v28
  v28-->v29
  v28-->v30
  v30-->v31
  v28-->v32
  v28-->v33
  v78-->v33
  v81-->v33
  v3-->v34
  v34-->v35
  v35-->v36
  v35-->v37
  v35-->v38
  v35-->v39
  v2-->v40
  v66-->v40
  v76-->v40
  v84-->v40
  v85-->v40
  v86-->v40
  v87-->v40
  v89-->v40
  v90-->v40
  v40-->v41
  v41-->v42
  v48-->v42
  v41-->v43
  v41-->v44
  v41-->v45
  v2-->v46
  v75-->v46
  v88-->v46
  v90-->v46
  v2-->v47
  v75-->v47
  v47-->v48
  v48-->v49
  v49-->v50
  v48-->v51
  v51-->v52
  v48-->v53
  v48-->v54
  v48-->v55
  v48-->v56
  v48-->v57
  v48-->v58
  v20-->v59
  v20-->v60
  v20-->v61
  v20-->v62
  v20-->v63
  v20-->v64
  v47-->v65
  v65-->v66
  v47-->v67
  v67-->v68
  v67-->v69
  v67-->v70
  v67-->v71
  v67-->v72
  v67-->v73
  v2-->v74
  v0-->v75
  v75-->v76
  v87-->v76
  v89-->v76
  v91-->v76
  v76-->v77
  v75-->v78
  v78-->v79
  v78-->v80
  v78-->v81
  v78-->v82
  v82-->v83
  v75-->v84
  v85-->v84
  v88-->v84
  v84-->v85
  v75-->v86
  v86-->v87
  v75-->v88
  v86-->v88
  v87-->v88
  v89-->v88
  v86-->v89
  v89-->v90
  v91-->v90
  v75-->v91
  v75-->v92
  v91-->v92
