graph TD;
  v0("wlr/backend.h")
  v90("wlr/render/dmabuf.h")
  v87("wlr/render/pass.h")
  v86("wlr/render/wlr_renderer.h")
  v89("wlr/render/wlr_texture.h")
  v91("wlr/types/wlr_buffer.h")
  v75("wlr/types/wlr_output.h")
  v92("wlr/util/addon.h")
  v88("wlr/util/box.h")
  v0-->v75
  v75-->v86
  v86-->v87
  v75-->v88
  v86-->v88
  v87-->v88
  v89-->v88
  v86-->v89
  v89-->v90
  v91-->v90
  v75-->v91
  v75-->v92
  v91-->v92
