graph TD;
  v2["/nix/store/blr5zdnxfckm1690cdx6anmh3s17sx5p-wayland-1.24.0-dev/include/wayland-server-core.h"]
  v84["/nix/store/blr5zdnxfckm1690cdx6anmh3s17sx5p-wayland-1.24.0-dev/include/wayland-server-protocol.h"]
  v85["/nix/store/blr5zdnxfckm1690cdx6anmh3s17sx5p-wayland-1.24.0-dev/include/wayland-server.h"]
  v47["/nix/store/blr5zdnxfckm1690cdx6anmh3s17sx5p-wayland-1.24.0-dev/include/wayland-util.h"]
  v74["/nix/store/blr5zdnxfckm1690cdx6anmh3s17sx5p-wayland-1.24.0-dev/include/wayland-version.h"]
  v0["/nix/store/f5cfc57shf92z97y0rawvcbhbl5zn080-wlroots-0.19.2/include/wlroots-0.19/wlr/backend.h"]
  v90["/nix/store/f5cfc57shf92z97y0rawvcbhbl5zn080-wlroots-0.19.2/include/wlroots-0.19/wlr/render/dmabuf.h"]
  v87["/nix/store/f5cfc57shf92z97y0rawvcbhbl5zn080-wlroots-0.19.2/include/wlroots-0.19/wlr/render/pass.h"]
  v86["/nix/store/f5cfc57shf92z97y0rawvcbhbl5zn080-wlroots-0.19.2/include/wlroots-0.19/wlr/render/wlr_renderer.h"]
  v89["/nix/store/f5cfc57shf92z97y0rawvcbhbl5zn080-wlroots-0.19.2/include/wlroots-0.19/wlr/render/wlr_texture.h"]
  v91["/nix/store/f5cfc57shf92z97y0rawvcbhbl5zn080-wlroots-0.19.2/include/wlroots-0.19/wlr/types/wlr_buffer.h"]
  v75["/nix/store/f5cfc57shf92z97y0rawvcbhbl5zn080-wlroots-0.19.2/include/wlroots-0.19/wlr/types/wlr_output.h"]
  v92["/nix/store/f5cfc57shf92z97y0rawvcbhbl5zn080-wlroots-0.19.2/include/wlroots-0.19/wlr/util/addon.h"]
  v88["/nix/store/f5cfc57shf92z97y0rawvcbhbl5zn080-wlroots-0.19.2/include/wlroots-0.19/wlr/util/box.h"]
  v37["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/atomic_wide_counter.h"]
  v26["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/byteswap.h"]
  v24["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/endian.h"]
  v25["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/endianness.h"]
  v52["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/floatn-common.h"]
  v51["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/floatn.h"]
  v53["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/flt-eval-method.h"]
  v55["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/fp-fast.h"]
  v54["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/fp-logb.h"]
  v42["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/libc-header-start.h"]
  v50["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/libm-simd-decl-stubs.h"]
  v10["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/long-double.h"]
  v49["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/math-vector.h"]
  v57["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/mathcalls-helper-functions.h"]
  v56["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/mathcalls-macros.h"]
  v58["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/mathcalls.h"]
  v36["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/pthreadtypes-arch.h"]
  v34["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/pthreadtypes.h"]
  v29["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/select.h"]
  v22["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/stdint-intn.h"]
  v45["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/stdint-least.h"]
  v44["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/stdint-uintn.h"]
  v38["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/struct_mutex.h"]
  v39["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/struct_rwlock.h"]
  v35["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/thread-shared-types.h"]
  v79["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/time.h"]
  v15["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/time64.h"]
  v7["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/timesize.h"]
  v13["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/types.h"]
  v83["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/types/__locale_t.h"]
  v31["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/types/__sigset_t.h"]
  v16["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/types/clock_t.h"]
  v17["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/types/clockid_t.h"]
  v82["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/types/locale_t.h"]
  v30["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/types/sigset_t.h"]
  v81["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/types/struct_itimerspec.h"]
  v33["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/types/struct_timespec.h"]
  v32["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/types/struct_timeval.h"]
  v80["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/types/struct_tm.h"]
  v18["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/types/time_t.h"]
  v19["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/types/timer_t.h"]
  v14["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/typesizes.h"]
  v27["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/uintn-identity.h"]
  v43["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/wchar.h"]
  v6["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/bits/wordsize.h"]
  v23["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/endian.h"]
  v5["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/features-time64.h"]
  v4["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/features.h"]
  v12["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/gnu/stubs-64.h"]
  v11["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/gnu/stubs.h"]
  v66["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/inttypes.h"]
  v48["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/math.h"]
  v8["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/stdc-predef.h"]
  v41["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/stdint.h"]
  v9["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/sys/cdefs.h"]
  v28["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/sys/select.h"]
  v3["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/sys/types.h"]
  v78["/nix/store/j8irrc0mpx029dw0rmadsjylg7h31ync-glibc-2.42-51-dev/include/time.h"]
  v77["/nix/store/s60msvirzaknyjgpsc8yyld1qg5i3hn5-pixman-0.46.4/include/pixman-version.h"]
  v76["/nix/store/s60msvirzaknyjgpsc8yyld1qg5i3hn5-pixman-0.46.4/include/pixman.h"]
  v69["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/__stdarg___gnuc_va_list.h"]
  v72["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/__stdarg___va_copy.h"]
  v68["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/__stdarg_header_macro.h"]
  v71["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/__stdarg_va_arg.h"]
  v73["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/__stdarg_va_copy.h"]
  v70["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/__stdarg_va_list.h"]
  v59["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/__stddef_header_macro.h"]
  v63["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/__stddef_max_align_t.h"]
  v62["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/__stddef_null.h"]
  v64["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/__stddef_offsetof.h"]
  v60["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/__stddef_ptrdiff_t.h"]
  v21["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/__stddef_size_t.h"]
  v61["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/__stddef_wchar_t.h"]
  v65["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/inttypes.h"]
  v67["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/stdarg.h"]
  v46["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/stdbool.h"]
  v20["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/stddef.h"]
  v40["/nix/store/y8xj70yyzsml4z3aa5gsn9pvpx4za1py-clang-wrapper-21.1.8/resource-root/include/stdint.h"]
  v0-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v85-->|"#include &quot;wayland-server-core.h&quot;"|v2
  v86-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v87-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v89-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v91-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v92-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v2-->|"#include &lt;sys/types.h&gt;"|v3
  v3-->|"#include &lt;features.h&gt;"|v4
  v13-->|"#include &lt;features.h&gt;"|v4
  v23-->|"#include &lt;features.h&gt;"|v4
  v26-->|"#include &lt;features.h&gt;"|v4
  v28-->|"#include &lt;features.h&gt;"|v4
  v42-->|"#include &lt;features.h&gt;"|v4
  v51-->|"#include &lt;features.h&gt;"|v4
  v52-->|"#include &lt;features.h&gt;"|v4
  v66-->|"#include &lt;features.h&gt;"|v4
  v78-->|"#include &lt;features.h&gt;"|v4
  v4-->|"#include &lt;features-time64.h&gt;"|v5
  v5-->|"#include &lt;bits/wordsize.h&gt;"|v6
  v7-->|"#include &lt;bits/wordsize.h&gt;"|v6
  v9-->|"#include &lt;bits/wordsize.h&gt;"|v6
  v13-->|"#include &lt;bits/wordsize.h&gt;"|v6
  v36-->|"#include &lt;bits/wordsize.h&gt;"|v6
  v41-->|"#include &lt;bits/wordsize.h&gt;"|v6
  v5-->|"#include &lt;bits/timesize.h&gt;"|v7
  v13-->|"#include &lt;bits/timesize.h&gt;"|v7
  v4-->|"#include &lt;stdc-predef.h&gt;"|v8
  v4-->|"#include &lt;sys/cdefs.h&gt;"|v9
  v9-->|"#include &lt;bits/long-double.h&gt;"|v10
  v52-->|"#include &lt;bits/long-double.h&gt;"|v10
  v4-->|"#include &lt;gnu/stubs.h&gt;"|v11
  v11-->|"#include &lt;gnu/stubs-64.h&gt;"|v12
  v3-->|"#include &lt;bits/types.h&gt;"|v13
  v16-->|"#include &lt;bits/types.h&gt;"|v13
  v17-->|"#include &lt;bits/types.h&gt;"|v13
  v18-->|"#include &lt;bits/types.h&gt;"|v13
  v19-->|"#include &lt;bits/types.h&gt;"|v13
  v22-->|"#include &lt;bits/types.h&gt;"|v13
  v26-->|"#include &lt;bits/types.h&gt;"|v13
  v27-->|"#include &lt;bits/types.h&gt;"|v13
  v28-->|"#include &lt;bits/types.h&gt;"|v13
  v32-->|"#include &lt;bits/types.h&gt;"|v13
  v33-->|"#include &lt;bits/types.h&gt;"|v13
  v41-->|"#include &lt;bits/types.h&gt;"|v13
  v44-->|"#include &lt;bits/types.h&gt;"|v13
  v45-->|"#include &lt;bits/types.h&gt;"|v13
  v48-->|"#include &lt;bits/types.h&gt;"|v13
  v79-->|"#include &lt;bits/types.h&gt;"|v13
  v80-->|"#include &lt;bits/types.h&gt;"|v13
  v81-->|"#include &lt;bits/types.h&gt;"|v13
  v13-->|"#include &lt;bits/typesizes.h&gt;"|v14
  v13-->|"#include &lt;bits/time64.h&gt;"|v15
  v3-->|"#include &lt;bits/types/clock_t.h&gt;"|v16
  v78-->|"#include &lt;bits/types/clock_t.h&gt;"|v16
  v3-->|"#include &lt;bits/types/clockid_t.h&gt;"|v17
  v78-->|"#include &lt;bits/types/clockid_t.h&gt;"|v17
  v3-->|"#include &lt;bits/types/time_t.h&gt;"|v18
  v28-->|"#include &lt;bits/types/time_t.h&gt;"|v18
  v33-->|"#include &lt;bits/types/time_t.h&gt;"|v18
  v78-->|"#include &lt;bits/types/time_t.h&gt;"|v18
  v3-->|"#include &lt;bits/types/timer_t.h&gt;"|v19
  v78-->|"#include &lt;bits/types/timer_t.h&gt;"|v19
  v3-->|"#include &lt;stddef.h&gt;"|v20
  v47-->|"#include &lt;stddef.h&gt;"|v20
  v78-->|"#include &lt;stddef.h&gt;"|v20
  v84-->|"#include &lt;stddef.h&gt;"|v20
  v20-->|"#include &lt;__stddef_size_t.h&gt;"|v21
  v3-->|"#include &lt;bits/stdint-intn.h&gt;"|v22
  v41-->|"#include &lt;bits/stdint-intn.h&gt;"|v22
  v3-->|"#include &lt;endian.h&gt;"|v23
  v23-->|"#include &lt;bits/endian.h&gt;"|v24
  v33-->|"#include &lt;bits/endian.h&gt;"|v24
  v24-->|"#include &lt;bits/endianness.h&gt;"|v25
  v23-->|"#include &lt;bits/byteswap.h&gt;"|v26
  v23-->|"#include &lt;bits/uintn-identity.h&gt;"|v27
  v3-->|"#include &lt;sys/select.h&gt;"|v28
  v28-->|"#include &lt;bits/select.h&gt;"|v29
  v28-->|"#include &lt;bits/types/sigset_t.h&gt;"|v30
  v30-->|"#include &lt;bits/types/__sigset_t.h&gt;"|v31
  v28-->|"#include &lt;bits/types/struct_timeval.h&gt;"|v32
  v28-->|"#include &lt;bits/types/struct_timespec.h&gt;"|v33
  v78-->|"#include &lt;bits/types/struct_timespec.h&gt;"|v33
  v81-->|"#include &lt;bits/types/struct_timespec.h&gt;"|v33
  v3-->|"#include &lt;bits/pthreadtypes.h&gt;"|v34
  v34-->|"#include &lt;bits/thread-shared-types.h&gt;"|v35
  v35-->|"#include &lt;bits/pthreadtypes-arch.h&gt;"|v36
  v35-->|"#include &lt;bits/atomic_wide_counter.h&gt;"|v37
  v35-->|"#include &lt;bits/struct_mutex.h&gt;"|v38
  v35-->|"#include &lt;bits/struct_rwlock.h&gt;"|v39
  v2-->|"#include &lt;stdint.h&gt;"|v40
  v66-->|"#include &lt;stdint.h&gt;"|v40
  v76-->|"#include &lt;stdint.h&gt;"|v40
  v84-->|"#include &lt;stdint.h&gt;"|v40
  v85-->|"#include &lt;stdint.h&gt;"|v40
  v86-->|"#include &lt;stdint.h&gt;"|v40
  v87-->|"#include &lt;stdint.h&gt;"|v40
  v89-->|"#include &lt;stdint.h&gt;"|v40
  v90-->|"#include &lt;stdint.h&gt;"|v40
  v40-->|"#include_next &lt;stdint.h&gt;"|v41
  v41-->|"#include &lt;bits/libc-header-start.h&gt;"|v42
  v48-->|"#include &lt;bits/libc-header-start.h&gt;"|v42
  v41-->|"#include &lt;bits/wchar.h&gt;"|v43
  v41-->|"#include &lt;bits/stdint-uintn.h&gt;"|v44
  v41-->|"#include &lt;bits/stdint-least.h&gt;"|v45
  v2-->|"#include &lt;stdbool.h&gt;"|v46
  v75-->|"#include &lt;stdbool.h&gt;"|v46
  v88-->|"#include &lt;stdbool.h&gt;"|v46
  v90-->|"#include &lt;stdbool.h&gt;"|v46
  v2-->|"#include &quot;wayland-util.h&quot;"|v47
  v75-->|"#include &lt;wayland-util.h&gt;"|v47
  v47-->|"#include &lt;math.h&gt;"|v48
  v48-->|"#include &lt;bits/math-vector.h&gt;"|v49
  v49-->|"#include &lt;bits/libm-simd-decl-stubs.h&gt;"|v50
  v48-->|"#include &lt;bits/floatn.h&gt;"|v51
  v51-->|"#include &lt;bits/floatn-common.h&gt;"|v52
  v48-->|"#include &lt;bits/flt-eval-method.h&gt;"|v53
  v48-->|"#include &lt;bits/fp-logb.h&gt;"|v54
  v48-->|"#include &lt;bits/fp-fast.h&gt;"|v55
  v48-->|"#include &lt;bits/mathcalls-macros.h&gt;"|v56
  v48-->|"#include &lt;bits/mathcalls-helper-functions.h&gt;"|v57
  v48-->|"#include &lt;bits/mathcalls.h&gt;"|v58
  v20-->|"#include &lt;__stddef_header_macro.h&gt;"|v59
  v20-->|"#include &lt;__stddef_ptrdiff_t.h&gt;"|v60
  v20-->|"#include &lt;__stddef_wchar_t.h&gt;"|v61
  v20-->|"#include &lt;__stddef_null.h&gt;"|v62
  v20-->|"#include &lt;__stddef_max_align_t.h&gt;"|v63
  v20-->|"#include &lt;__stddef_offsetof.h&gt;"|v64
  v47-->|"#include &lt;inttypes.h&gt;"|v65
  v65-->|"#include_next &lt;inttypes.h&gt;"|v66
  v47-->|"#include &lt;stdarg.h&gt;"|v67
  v67-->|"#include &lt;__stdarg_header_macro.h&gt;"|v68
  v67-->|"#include &lt;__stdarg___gnuc_va_list.h&gt;"|v69
  v67-->|"#include &lt;__stdarg_va_list.h&gt;"|v70
  v67-->|"#include &lt;__stdarg_va_arg.h&gt;"|v71
  v67-->|"#include &lt;__stdarg___va_copy.h&gt;"|v72
  v67-->|"#include &lt;__stdarg_va_copy.h&gt;"|v73
  v2-->|"#include &quot;wayland-version.h&quot;"|v74
  v0-->|"#include &lt;wlr/types/wlr_output.h&gt;"|v75
  v75-->|"#include &lt;pixman.h&gt;"|v76
  v87-->|"#include &lt;pixman.h&gt;"|v76
  v89-->|"#include &lt;pixman.h&gt;"|v76
  v91-->|"#include &lt;pixman.h&gt;"|v76
  v76-->|"#include &lt;pixman-version.h&gt;"|v77
  v75-->|"#include &lt;time.h&gt;"|v78
  v78-->|"#include &lt;bits/time.h&gt;"|v79
  v78-->|"#include &lt;bits/types/struct_tm.h&gt;"|v80
  v78-->|"#include &lt;bits/types/struct_itimerspec.h&gt;"|v81
  v78-->|"#include &lt;bits/types/locale_t.h&gt;"|v82
  v82-->|"#include &lt;bits/types/__locale_t.h&gt;"|v83
  v75-->|"#include &lt;wayland-server-protocol.h&gt;"|v84
  v85-->|"#include &quot;wayland-server-protocol.h&quot;"|v84
  v88-->|"#include &lt;wayland-server-protocol.h&gt;"|v84
  v84-->|"#include &quot;wayland-server.h&quot;"|v85
  v75-->|"#include &lt;wlr/render/wlr_renderer.h&gt;"|v86
  v86-->|"#include &lt;wlr/render/pass.h&gt;"|v87
  v75-->|"#include &lt;wlr/util/box.h&gt;"|v88
  v86-->|"#include &lt;wlr/util/box.h&gt;"|v88
  v87-->|"#include &lt;wlr/util/box.h&gt;"|v88
  v89-->|"#include &lt;wlr/util/box.h&gt;"|v88
  v86-->|"#include &lt;wlr/render/wlr_texture.h&gt;"|v89
  v89-->|"#include &lt;wlr/render/dmabuf.h&gt;"|v90
  v91-->|"#include &lt;wlr/render/dmabuf.h&gt;"|v90
  v75-->|"#include &lt;wlr/types/wlr_buffer.h&gt;"|v91
  v75-->|"#include &lt;wlr/util/addon.h&gt;"|v92
  v91-->|"#include &lt;wlr/util/addon.h&gt;"|v92
