%% Manually edited reduced include graph.

graph TD;
  v0["wlr/backend.h"]
  v29["wayland-util.h"]
  v57["Pixman"]
  v95["wlr/types/wlr_output.h"]
  v98["Wayland server"]
  v99["Other wlroots sub-headers"]
  v0-->v98
  v99-->v98
  v98-->v29
  v99-->v29
  v0-->v95
  v95-->v99
  v99-->v57
