graph TD;
  v58["/nix/store/1cnvyk57f3wqlmbpidz0x2824ip9f8ly-pixman-0.46.4/include/pixman-version.h"]
  v57["/nix/store/1cnvyk57f3wqlmbpidz0x2824ip9f8ly-pixman-0.46.4/include/pixman.h"]
  v50["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/__stdarg___gnuc_va_list.h"]
  v53["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/__stdarg___va_copy.h"]
  v49["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/__stdarg_header_macro.h"]
  v52["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/__stdarg_va_arg.h"]
  v54["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/__stdarg_va_copy.h"]
  v51["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/__stdarg_va_list.h"]
  v40["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/__stddef_header_macro.h"]
  v44["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/__stddef_max_align_t.h"]
  v43["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/__stddef_null.h"]
  v45["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/__stddef_offsetof.h"]
  v41["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/__stddef_ptrdiff_t.h"]
  v20["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/__stddef_size_t.h"]
  v42["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/__stddef_wchar_t.h"]
  v46["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/inttypes.h"]
  v48["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/stdarg.h"]
  v28["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/stdbool.h"]
  v19["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/stddef.h"]
  v22["/nix/store/351bpjcf2l1n4vm06nwpq3cdhl6vbhx1-clang-wrapper-21.1.7/resource-root/include/stdint.h"]
  v2["/nix/store/c3q7cp0nbvndl38znhqw3daihnirqj3g-wayland-1.24.0-dev/include/wayland-server-core.h"]
  v66["/nix/store/c3q7cp0nbvndl38znhqw3daihnirqj3g-wayland-1.24.0-dev/include/wayland-server-protocol.h"]
  v67["/nix/store/c3q7cp0nbvndl38znhqw3daihnirqj3g-wayland-1.24.0-dev/include/wayland-server.h"]
  v29["/nix/store/c3q7cp0nbvndl38znhqw3daihnirqj3g-wayland-1.24.0-dev/include/wayland-util.h"]
  v55["/nix/store/c3q7cp0nbvndl38znhqw3daihnirqj3g-wayland-1.24.0-dev/include/wayland-version.h"]
  v64["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/endian.h"]
  v65["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/endianness.h"]
  v34["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/floatn-common.h"]
  v33["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/floatn.h"]
  v35["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/flt-eval-method.h"]
  v37["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/fp-fast.h"]
  v36["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/fp-logb.h"]
  v24["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/libc-header-start.h"]
  v32["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/libm-simd-decl-stubs.h"]
  v10["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/long-double.h"]
  v31["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/math-vector.h"]
  v38["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/mathcalls-helper-functions.h"]
  v39["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/mathcalls.h"]
  v21["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/stdint-intn.h"]
  v27["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/stdint-least.h"]
  v26["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/stdint-uintn.h"]
  v60["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/time.h"]
  v15["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/time64.h"]
  v7["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/timesize.h"]
  v13["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/types.h"]
  v61["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/types/clock_t.h"]
  v16["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/types/clockid_t.h"]
  v63["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/types/struct_timespec.h"]
  v62["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/types/struct_tm.h"]
  v17["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/types/time_t.h"]
  v18["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/types/timer_t.h"]
  v14["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/typesizes.h"]
  v25["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/wchar.h"]
  v6["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/bits/wordsize.h"]
  v5["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/features-time64.h"]
  v4["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/features.h"]
  v12["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/gnu/stubs-64.h"]
  v11["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/gnu/stubs.h"]
  v47["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/inttypes.h"]
  v30["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/math.h"]
  v8["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/stdc-predef.h"]
  v23["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/stdint.h"]
  v9["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/sys/cdefs.h"]
  v3["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/sys/types.h"]
  v59["/nix/store/dj43clc5ff7jjnfmhbaj6q4q0h8kpfpm-glibc-2.40-66-dev/include/time.h"]
  v0["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/backend.h"]
  v72["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/render/dmabuf.h"]
  v69["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/render/pass.h"]
  v68["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/render/wlr_renderer.h"]
  v71["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/render/wlr_texture.h"]
  v73["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/types/wlr_buffer.h"]
  v56["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/types/wlr_output.h"]
  v74["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/util/addon.h"]
  v70["/nix/store/vxm9x8hynlq20jsm38waw7ji3qprd6rq-wlroots-0.19.2/include/wlroots-0.19/wlr/util/box.h"]
  v0-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v67-->|"#include &quot;wayland-server-core.h&quot;"|v2
  v68-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v69-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v71-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v73-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v74-->|"#include &lt;wayland-server-core.h&gt;"|v2
  v2-->|"#include &lt;sys/types.h&gt;"|v3
  v3-->|"#include &lt;features.h&gt;"|v4
  v13-->|"#include &lt;features.h&gt;"|v4
  v24-->|"#include &lt;features.h&gt;"|v4
  v33-->|"#include &lt;features.h&gt;"|v4
  v34-->|"#include &lt;features.h&gt;"|v4
  v47-->|"#include &lt;features.h&gt;"|v4
  v59-->|"#include &lt;features.h&gt;"|v4
  v4-->|"#include &lt;features-time64.h&gt;"|v5
  v5-->|"#include &lt;bits/wordsize.h&gt;"|v6
  v7-->|"#include &lt;bits/wordsize.h&gt;"|v6
  v9-->|"#include &lt;bits/wordsize.h&gt;"|v6
  v13-->|"#include &lt;bits/wordsize.h&gt;"|v6
  v23-->|"#include &lt;bits/wordsize.h&gt;"|v6
  v5-->|"#include &lt;bits/timesize.h&gt;"|v7
  v13-->|"#include &lt;bits/timesize.h&gt;"|v7
  v4-->|"#include &lt;stdc-predef.h&gt;"|v8
  v4-->|"#include &lt;sys/cdefs.h&gt;"|v9
  v9-->|"#include &lt;bits/long-double.h&gt;"|v10
  v34-->|"#include &lt;bits/long-double.h&gt;"|v10
  v4-->|"#include &lt;gnu/stubs.h&gt;"|v11
  v11-->|"#include &lt;gnu/stubs-64.h&gt;"|v12
  v3-->|"#include &lt;bits/types.h&gt;"|v13
  v16-->|"#include &lt;bits/types.h&gt;"|v13
  v17-->|"#include &lt;bits/types.h&gt;"|v13
  v18-->|"#include &lt;bits/types.h&gt;"|v13
  v21-->|"#include &lt;bits/types.h&gt;"|v13
  v23-->|"#include &lt;bits/types.h&gt;"|v13
  v26-->|"#include &lt;bits/types.h&gt;"|v13
  v27-->|"#include &lt;bits/types.h&gt;"|v13
  v30-->|"#include &lt;bits/types.h&gt;"|v13
  v60-->|"#include &lt;bits/types.h&gt;"|v13
  v61-->|"#include &lt;bits/types.h&gt;"|v13
  v62-->|"#include &lt;bits/types.h&gt;"|v13
  v63-->|"#include &lt;bits/types.h&gt;"|v13
  v13-->|"#include &lt;bits/typesizes.h&gt;"|v14
  v13-->|"#include &lt;bits/time64.h&gt;"|v15
  v3-->|"#include &lt;bits/types/clockid_t.h&gt;"|v16
  v3-->|"#include &lt;bits/types/time_t.h&gt;"|v17
  v59-->|"#include &lt;bits/types/time_t.h&gt;"|v17
  v63-->|"#include &lt;bits/types/time_t.h&gt;"|v17
  v3-->|"#include &lt;bits/types/timer_t.h&gt;"|v18
  v3-->|"#include &lt;stddef.h&gt;"|v19
  v29-->|"#include &lt;stddef.h&gt;"|v19
  v59-->|"#include &lt;stddef.h&gt;"|v19
  v66-->|"#include &lt;stddef.h&gt;"|v19
  v19-->|"#include &lt;__stddef_size_t.h&gt;"|v20
  v3-->|"#include &lt;bits/stdint-intn.h&gt;"|v21
  v23-->|"#include &lt;bits/stdint-intn.h&gt;"|v21
  v2-->|"#include &lt;stdint.h&gt;"|v22
  v47-->|"#include &lt;stdint.h&gt;"|v22
  v57-->|"#include &lt;stdint.h&gt;"|v22
  v66-->|"#include &lt;stdint.h&gt;"|v22
  v67-->|"#include &lt;stdint.h&gt;"|v22
  v68-->|"#include &lt;stdint.h&gt;"|v22
  v69-->|"#include &lt;stdint.h&gt;"|v22
  v71-->|"#include &lt;stdint.h&gt;"|v22
  v72-->|"#include &lt;stdint.h&gt;"|v22
  v22-->|"#include_next &lt;stdint.h&gt;"|v23
  v23-->|"#include &lt;bits/libc-header-start.h&gt;"|v24
  v30-->|"#include &lt;bits/libc-header-start.h&gt;"|v24
  v23-->|"#include &lt;bits/wchar.h&gt;"|v25
  v23-->|"#include &lt;bits/stdint-uintn.h&gt;"|v26
  v23-->|"#include &lt;bits/stdint-least.h&gt;"|v27
  v2-->|"#include &lt;stdbool.h&gt;"|v28
  v56-->|"#include &lt;stdbool.h&gt;"|v28
  v70-->|"#include &lt;stdbool.h&gt;"|v28
  v72-->|"#include &lt;stdbool.h&gt;"|v28
  v2-->|"#include &quot;wayland-util.h&quot;"|v29
  v56-->|"#include &lt;wayland-util.h&gt;"|v29
  v29-->|"#include &lt;math.h&gt;"|v30
  v30-->|"#include &lt;bits/math-vector.h&gt;"|v31
  v31-->|"#include &lt;bits/libm-simd-decl-stubs.h&gt;"|v32
  v30-->|"#include &lt;bits/floatn.h&gt;"|v33
  v33-->|"#include &lt;bits/floatn-common.h&gt;"|v34
  v30-->|"#include &lt;bits/flt-eval-method.h&gt;"|v35
  v30-->|"#include &lt;bits/fp-logb.h&gt;"|v36
  v30-->|"#include &lt;bits/fp-fast.h&gt;"|v37
  v30-->|"#include &lt;bits/mathcalls-helper-functions.h&gt;"|v38
  v30-->|"#include &lt;bits/mathcalls.h&gt;"|v39
  v19-->|"#include &lt;__stddef_header_macro.h&gt;"|v40
  v19-->|"#include &lt;__stddef_ptrdiff_t.h&gt;"|v41
  v19-->|"#include &lt;__stddef_wchar_t.h&gt;"|v42
  v19-->|"#include &lt;__stddef_null.h&gt;"|v43
  v19-->|"#include &lt;__stddef_max_align_t.h&gt;"|v44
  v19-->|"#include &lt;__stddef_offsetof.h&gt;"|v45
  v29-->|"#include &lt;inttypes.h&gt;"|v46
  v46-->|"#include_next &lt;inttypes.h&gt;"|v47
  v29-->|"#include &lt;stdarg.h&gt;"|v48
  v48-->|"#include &lt;__stdarg_header_macro.h&gt;"|v49
  v48-->|"#include &lt;__stdarg___gnuc_va_list.h&gt;"|v50
  v48-->|"#include &lt;__stdarg_va_list.h&gt;"|v51
  v48-->|"#include &lt;__stdarg_va_arg.h&gt;"|v52
  v48-->|"#include &lt;__stdarg___va_copy.h&gt;"|v53
  v48-->|"#include &lt;__stdarg_va_copy.h&gt;"|v54
  v2-->|"#include &quot;wayland-version.h&quot;"|v55
  v0-->|"#include &lt;wlr/types/wlr_output.h&gt;"|v56
  v56-->|"#include &lt;pixman.h&gt;"|v57
  v69-->|"#include &lt;pixman.h&gt;"|v57
  v71-->|"#include &lt;pixman.h&gt;"|v57
  v73-->|"#include &lt;pixman.h&gt;"|v57
  v57-->|"#include &lt;pixman-version.h&gt;"|v58
  v56-->|"#include &lt;time.h&gt;"|v59
  v59-->|"#include &lt;bits/time.h&gt;"|v60
  v59-->|"#include &lt;bits/types/clock_t.h&gt;"|v61
  v59-->|"#include &lt;bits/types/struct_tm.h&gt;"|v62
  v59-->|"#include &lt;bits/types/struct_timespec.h&gt;"|v63
  v63-->|"#include &lt;bits/endian.h&gt;"|v64
  v64-->|"#include &lt;bits/endianness.h&gt;"|v65
  v56-->|"#include &lt;wayland-server-protocol.h&gt;"|v66
  v67-->|"#include &quot;wayland-server-protocol.h&quot;"|v66
  v70-->|"#include &lt;wayland-server-protocol.h&gt;"|v66
  v66-->|"#include &quot;wayland-server.h&quot;"|v67
  v56-->|"#include &lt;wlr/render/wlr_renderer.h&gt;"|v68
  v68-->|"#include &lt;wlr/render/pass.h&gt;"|v69
  v56-->|"#include &lt;wlr/util/box.h&gt;"|v70
  v68-->|"#include &lt;wlr/util/box.h&gt;"|v70
  v69-->|"#include &lt;wlr/util/box.h&gt;"|v70
  v71-->|"#include &lt;wlr/util/box.h&gt;"|v70
  v68-->|"#include &lt;wlr/render/wlr_texture.h&gt;"|v71
  v71-->|"#include &lt;wlr/render/dmabuf.h&gt;"|v72
  v73-->|"#include &lt;wlr/render/dmabuf.h&gt;"|v72
  v56-->|"#include &lt;wlr/types/wlr_buffer.h&gt;"|v73
  v56-->|"#include &lt;wlr/util/addon.h&gt;"|v74
  v73-->|"#include &lt;wlr/util/addon.h&gt;"|v74
